baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
copyright: 🏍️
theme: xrazis
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "Software engineer, avid motorcyclist, occasional racer."
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  cdnUrl: https://cdn.xrazis.com

  assets:
    favicon32x32: "/favicon.png"

  label:
    text: Haris Razis

  homeParams:
    Title: Hey,
    Content: |
      I create bugs for a living, and this corner of the web is my digital garden — a small collection of things I’ve 
      learned and done over the years. Here, you’ll find my projects, technical insights, and stories from my adventures.
      
      After trying all sorts of hobbies, I've concluded that riding bikes and motorcycles is my thing. I've gotten 
      especially good at breaking bones, a true talent, one might say. For tales of cracked crankcases and lost 
      paperwork in distant lands, click the yellow highlighted dates and tags.
      
      My default handle is **xrazis**.
    Footer: Hakuna matata

  socialIcons:
    - name: Mastodon
      url: "https://mastodon.social/@xrazis"
    - name: Github
      url: "https://github.com/xrazis"
    - name: Linkedin
      url: "https://www.linkedin.com/in/xrazis/"
    - name: Email
      url: "mailto:haris@razis.com"
    - name: Signal
      url: "xrazis.66"

menu:
  main:
    - identifier: photos
      name: Photos
      url: /photos/
      weight: 10

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    style: obsidian-min