baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
paginate: 6
theme: hugo-PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "Software engineer, avid motorcyclist, occasional racer."
  keywords: [ Blog, Portfolio, PaperMod ]
  images: [ "./cup.png" ]
  DateFormat: "2 January, 2006"
  defaultTheme: dark
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false
  ShowPageNums: true
  ShowWordCount: true
  hideFooter: true

  assets:
    disableHLJS: false
    favicon32x32: "/favicon.png"

  label:
    text: "Haris Razis"

  profileMode:
    enabled: false # needs to be explicitly set

  homeInfoParams:
    Title: "Hey, I'm Haris"
    Content: >
      - I create bugs for a living, and this corner of the web is my digital garden — a small collection of things I’ve 
      learned over the years. Here, you’ll find my personal projects, technical insights, and stories from my motorcycle 
      adventures.
      
      - 
      
      - My default handle is **xrazis**.

  socialIcons:
    - name: github
      url: "https://github.com/xrazis"
    - name: linkedin
      url: "https://www.linkedin.com/in/xrazis/"
    - name: youtube
      url: "https://www.youtube.com/channel/UCF79v6s2uTSf8l4P_ud3hOw"
    - name: strava
      url: "https://www.strava.com/athletes/8027560"
    - name: email
      url: "mailto:haris@razis.com"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 100
    threshold: 0.4
    minMatchCharLength: 3
    keys: [ "title", "RelPermalink", "summary", "content" ]

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    style: obsidian-min