baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
copyright: 🏍️
theme: xrazis
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: ""
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  cdnUrl: https://cdn.xrazis.com/haris.razis.com/

  label:
    text: Haris Razis

  strings:
    home: |
      Hey, my name is Haris. I create bugs for a living, and this corner of the web is my digital garden — a small collection 
      of things I’ve learned and done over the years. Here you’ll read my technical insights and stories from my adventures.
      
      After trying all sorts of hobbies, I've concluded that riding bikes and motorcycles is my thing. I've gotten 
      especially good at breaking bones, a true talent, one might say. For tales of cracked crankcases and lost 
      paperwork in distant lands, click the yellow highlighted dates and tags.
      
      On the footer you will find ways to contact me, my Flickr that has some cool photos, and my Mastodon  where i microblog. 
      
      My default handle is **xrazis**.
    about: |
      ## WIP
      
      The old internet used to be much purer. Free of ads, paywalls, and walled garden social media. It was full of 
      unique and interesting blogs, where you could read the thoughts of like-minded individuals.

      This blog is my little contribution to the internet. After all, the internet is not a window to a better world, 
      it is a mirror. A mirror of us. We do not have to fix the internet. We have to fix ourselves. 
      
      ### Motorcycles and bikes
      
      Motorcycles are a lifestyle. It may sound cliché, and you've probably heard it before a thousand times, but stick with me. 
      
      The sense of freedom you get on a motorcycle is a unique feeling that no other vehicle can replicate. You are one with
      your surroundings and not sterilized in a metal box. You are part of a community where everyone helps each other 
      when in need, transcending age or sex, political or religious beliefs, and background. It is an emotional 
      experience, whether you are cruising by the coast or ripping trails on the mountains. You are in absolute synchronization
      with a vastly complex, but yet, so simple machine. 
      
      **Motorcycles are a way of life.**
      
      Bikes on the other hand are the simplest form of a motorcycle to my eyes — you get a new perspective of two-wheeled 
      vehicles dynamics.
      
      ### Weightlifting
      
      Science based lifting from the likes of [Jeff Nipard](https://www.youtube.com/@JeffNippard) and 
      [Renaissance Periodization](https://www.youtube.com/@RenaissancePeriodization) is my cup of tea. I train consistently
      with weights for a while now. I don't do 1 rep max efforts often as I deem them too risky. Instead,  I use
      a [one rep max calculator](https://exrx.net/Calculators/OneRepMax) to roughly get an idea of where I stand. 
      
      | Lift         | One rep max |
      | :----------: | :---------: |
      | **Squat**    | 110kg       |
      | **Bench**    | 82kg        |
      | **Deadlift** | 153kg       |
      
      Where that places me as a lifter? Well, given I am a little over 80 kilos and based on the table bellow from
      [Jeff](https://jeffnippard.com/blogs/news/how-strong-should-you-be-noob-to-freak-1), I am an early intermediate.
      
      |   Lift       | Beginner    | Intermediate  | Advanced     | Elite       | Freak       |
      | :----------: | :---------: | :-----------: | :---------:  | :---------: | :---------: |
      | **Squat**    | 1.25X BW    | 1.25-1.75X BW | 1.75-1.5X BW | 2.5-3X BW   | 3X+ BW      |
      | **Bench**    | 1X BW       | 1-1.5X BW     | 1.5-2X BW    | 2-2.25X BW  | 2.25X+ BW   |
      | **Deadlift** | 1.5X BW     | 1.5-2.25X BW  | 2.25-3X BW   | 3-3.5X BW   | 3.5X+ BW    |
      
      ### Film photography
      
      At first I thought it was quite stupid to shoot on film in an age where the average smartphone is more than enough
      to cover your needs. I continued to believe it up until my friend Christos gave me printed photos of a trip we had. 
      Next thing you know, I was out buying film for a 90's point and shoot we had laying around.
      
      Of course you can emulate the _feeling_ of a film camera on a photo. And of course you can print your high quality digital
      photos. But, what I really like, is that naive feeling when you shoot. The fact that you have one chance to get a good shot.
      Waiting for the film to develop, anxious to see if you got any good shots. The photos you have lying around the house, that 
      you then pass around to your friends to see. 
      
      ### Blogroll
      
      These are some of the blogs I enjoy reading:
      
      - [Tania Rascia](https://www.taniarascia.com/)
      - [Alex Hyett](https://www.alexhyett.com/)
      - [JP Hastings-Edrei](https://www.byjp.me/)
    footer: Hakuna matata

  socialIcons:
    - name: Signal
      url: "https://signal.me/#eu/FY5rnVgkfidSiO-Tt0qgLM_DuaoiAVOEP-GaBVmjaRviDz6bSGtKWJ43XOfVuB1_"
    - name: Email
      url: "mailto:haris@razis.com"
    - name: Mastodon
      url: "https://mastodon.social/@xrazis"
    - name: Github
      url: "https://github.com/xrazis"
    - name: Flickr
      url: "https://flickr.com/photos/202360067@N06"
    - name: Linkedin
      url: "https://www.linkedin.com/in/xrazis/"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    style: obsidian-min