baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
copyright: 🏍️
theme: xrazis
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "Software engineer, avid motorcyclist, occasional racer."
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  cdnUrl: https://cdn.xrazis.com/static

  assets:
    favicon32x32: "/favicon.png"

  label:
    text: Haris Razis

  strings:
    home: |
      Hey, my name is Haris. I create bugs for a living, and this corner of the web is my digital garden — a small collection 
      of things I’ve learned and done over the years. Here, you’ll find my projects, technical insights, and stories 
      from my adventures.
      
      After trying all sorts of hobbies, I've concluded that riding bikes and motorcycles is my thing. I've gotten 
      especially good at breaking bones, a true talent, one might say. For tales of cracked crankcases and lost 
      paperwork in distant lands, click the yellow highlighted dates and tags.
      
      My default handle is **xrazis**.
    about: |
      The old internet used to be much purer. Free of ads, paywalls, and walled garden social media. It was full of 
      unique and interesting blogs, where you could read the thoughts of like-minded individuals. Although I am not old 
      enough to have lived that long-gone era, I've been told the tales and seen the relics. An era where social 
      media did not exist as censorship, democracy manipulative, and ad-revenue tools.

      Do not get me wrong; I am not (overly) judgmental of what the internet has evolved to. For 
      instance, I do believe that social media is worth (some of) your time — you can meet and connect with a lot of 
      cool people. But I also believe that they do not work in their current centralized form. That's why I microblog on 
      [Mastodon](https://joinmastodon.org/). It is exactly how I imagine social media. Open source, free, decentralized,
      and federated.
      
      Besides microblogging, here you will read the long, 'proper', blogs. There is no particular content or purpose for 
      this blog, it is just my corner of the web. My little contribution to the internet.
      
      After all, the internet is not a window to a better world, it is a mirror. A mirror of us. 
      We do not have to fix the internet. We have to fix ourselves. 
      
      ### Motorcycles
      
      ### Mountain bikes
      
      ### Weightlifting
      
      Science based lifting from the likes of [Jeff Nipard](https://www.youtube.com/@JeffNippard) and 
      [Renaissance Periodization](https://www.youtube.com/@RenaissancePeriodization) is my cup of tea. I train consistently
      with weights for a while now. I don't do 1 rep max efforts often as I deem them too risky. Instead,  I use
      a [one rep max calculator](https://exrx.net/Calculators/OneRepMax) to roughly get an idea of where I stand. 
      
      | Lift         | One rep max |
      | :----------: | :---------: |
      | **Squat**    | 109kg       |
      | **Bench**    | 82kg        |
      | **Deadlift** | 142kg       |
      
      Where that places me as a lifter? Well, given I am a little over 80 kilos and based on the table bellow from
      [Jeff](https://jeffnippard.com/blogs/news/how-strong-should-you-be-noob-to-freak-1), I am an early intermediate.
      
      |   Lift       | Beginner    | Intermediate  | Advanced     | Elite       | Freak       |
      | :----------: | :---------: | :-----------: | :---------:  | :---------: | :---------: |
      | **Squat**    | 1.25X BW    | 1.25-1.75X BW | 1.75-1.5X BW | 2.5-3X BW   | 3X+ BW      |
      | **Bench**    | 1X BW       | 1-1.5X BW     | 1.5-2X BW    | 2-2.25X BW  | 2.25X+ BW   |
      | **Deadlift** | 1.5X BW     | 1.5-2.25X BW  | 2.25-3X BW   | 3-3.5X BW   | 3.5X+ BW    |
      
      ### Film photography
      
      ### Blogroll
      
      These are the blogs I enjoy reading:
      
      - Entry 1
      - Entry 2
      - Entry 3
    multimedia: |
      WIP! I share little on social media, but I do have some nice shots worth seeing. Coming soon!
      
      Second line
    footer: Hakuna matata

  socialIcons:
    - name: Signal
      url: "https://signal.me/#eu/FY5rnVgkfidSiO-Tt0qgLM_DuaoiAVOEP-GaBVmjaRviDz6bSGtKWJ43XOfVuB1_"
    - name: Email
      url: "mailto:haris@razis.com"
    - name: Mastodon
      url: "https://mastodon.social/@xrazis"
    - name: Github
      url: "https://github.com/xrazis"
    - name: Linkedin
      url: "https://www.linkedin.com/in/xrazis/"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    style: obsidian-min