baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
paginate: 6
theme: hugo-PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "My personal website"
  keywords: [ Blog, Portfolio, PaperMod ]
  images: [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat: "2 January, 2006"
  defaultTheme: dark
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    favicon32x32: "/favicon.png"

  label:
    text: "xrazis"

  profileMode:
    enabled: false # needs to be explicitly set

  homeInfoParams:
    Title: "My name is Haris Razis"
    Content: >
      - I’m a software engineer and a great guy. This corner of the web is my digital garden, a small collection
      of things I’ve learned over the years. 
      
      -
      
      - My default handle is **xrazis**.

  socialIcons:
    - name: github
      url: "https://github.com/xrazis"
    - name: linkedin
      url: "https://www.linkedin.com/in/xrazis/"
    - name: facebook
      url: "https://www.facebook.com/xrazis"
    - name: youtube
      url: "https://www.youtube.com/channel/UCF79v6s2uTSf8l4P_ud3hOw"
    - name: strava
      url: "https://www.strava.com/athletes/8027560"
    - name: email
      url: "mailto:haris@razis.com"
    - name: pgp
      url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0f4fe426d8f9f955f5e625b17bd748cfb62474de"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xrazis/haris.razis.com/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 100
    threshold: 0.4
    minMatchCharLength: 3
    keys: [ "title", "RelPermalink", "summary", "content" ]

menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    # noClasses: false
    style: github-dark