baseURL: "https://xrazis.com/"
title: Haris Razis - SE
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "My personal blog-portfolio"
  keywords: [ Blog, Portfolio, PaperMod ]
  author: Haris Razis
  images: [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat: "2 January, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "xrazis"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    Title: "Hi there 🤙"
    Content: I am Haris, a software engineer and a great guy.

  socialIcons:
    - name: github
      url: "https://github.com/xrazis"
    - name: twitter
      url: "https://twitter.com/x_razis"
    - name: linkedin
      url: "https://www.linkedin.com/in/xrazis/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xrazis/xrazis/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON
