baseURL: "https://haris.razis.com/"
title: xrazis · Haris Razis
copyright: 🏍️
theme: xrazis
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: xrazis
  description: "Software engineer, avid motorcyclist, occasional racer."
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  cdnUrl: https://cdn.xrazis.com/static

  assets:
    favicon32x32: "/favicon.png"

  label:
    text: Haris Razis

  strings:
    home: |
      Hey, my name is Haris. I create bugs for a living, and this corner of the web is my digital garden — a small collection 
      of things I’ve learned and done over the years. Here, you’ll find my projects, technical insights, and stories 
      from my adventures.
      
      After trying all sorts of hobbies, I've concluded that riding bikes and motorcycles is my thing. I've gotten 
      especially good at breaking bones, a true talent, one might say. For tales of cracked crankcases and lost 
      paperwork in distant lands, click the yellow highlighted dates and tags.
      
      My default handle is **xrazis**.
    about: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
      aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
      Duis aute irure dolor in reprehenderit in voluptate.
    multimedia: WIP! I share little on social media, but I do have some nice shots worth seeing. Coming soon!
    footer: Hakuna matata

  socialIcons:
    - name: Signal
      url: "https://signal.me/#eu/FY5rnVgkfidSiO-Tt0qgLM_DuaoiAVOEP-GaBVmjaRviDz6bSGtKWJ43XOfVuB1_"
    - name: Email
      url: "mailto:haris@razis.com"
    - name: Mastodon
      url: "https://mastodon.social/@xrazis"
    - name: Github
      url: "https://github.com/xrazis"
    - name: Linkedin
      url: "https://www.linkedin.com/in/xrazis/"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

outputs:
  home:
    - HTML
    - JSON

markup:
  highlight:
    style: obsidian-min